# Generated by Django 5.2.1 on 2025-05-23 18:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('connection_type', models.CharField(choices=[('Fiber', 'Fiber'), ('DSL', 'DSL'), ('Broadband', 'Broadband')], max_length=50)),
                ('connection_date', models.DateTimeField(auto_now_add=True)),
                ('wifi_plan', models.CharField(choices=[('Basic-5', 'Basic - 5 Mbps'), ('Standard-10', 'Standard - 10 Mbps'), ('Premium-100', 'Premium - 100 Mbps'), ('Ultra-200', 'Ultra - 200 Mbps')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
